# Generated by Django 5.1.4 on 2025-02-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workbook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DotProductProblem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.JSONField()),
                ("answer", models.JSONField()),
            ],
        ),
    ]
